# Generated by Django 3.2.4 on 2021-06-20 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categorie',
            table=None,
        ),
    ]
