# Generated by Django 3.2.4 on 2021-06-20 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0002_alter_categorie_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categorie',
            table='categorie',
        ),
    ]
