# Generated by Django 3.2.4 on 2021-06-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0003_alter_categorie_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='CategorieDetails',
        ),
    ]
